import type { Destination } from './types';

/** Curated seed destinations with experience windows for the Kairos engine. */
export const DESTINATIONS: Destination[] = [
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    timezoneOffset: 0,
    tagline: 'Hills, light, and tiled silence between tram bells.',
    experiences: [
      {
        id: 'lx-miradouro',
        name: 'Miradouro da Senhora do Monte',
        kind: 'viewpoint',
        durationHours: 1,
        walkingCostKm: 1.2,
        decisionLoad: 0.15,
        regretWeight: 0.85,
        window: {
          peakHour: 7.5,
          peakWidth: 1.5,
          crowdAtPeak: 0.25,
          lightAffinity: 'dawn',
        },
        priorityTags: ['photo', 'nature'],
        description: 'City roofscape at first light — soft gold before the heat.',
      },
      {
        id: 'lx-jeronimos',
        name: 'Mosteiro dos Jerónimos',
        kind: 'museum',
        durationHours: 2,
        walkingCostKm: 0.8,
        decisionLoad: 0.45,
        regretWeight: 0.7,
        window: {
          peakHour: 9.5,
          peakWidth: 2,
          crowdAtPeak: 0.55,
          lightAffinity: 'day',
        },
        priorityTags: ['culture'],
        description: 'Manueline stone and cloisters before tour groups peak.',
      },
      {
        id: 'lx-timeout',
        name: 'Time Out Market lunch',
        kind: 'market',
        durationHours: 1.5,
        walkingCostKm: 0.5,
        decisionLoad: 0.7,
        regretWeight: 0.35,
        window: {
          peakHour: 12.5,
          peakWidth: 1.5,
          crowdAtPeak: 0.85,
          lightAffinity: 'day',
        },
        priorityTags: ['food'],
        description: 'Food hall energy — best slightly off the noon crush.',
      },
      {
        id: 'lx-alfama',
        name: 'Alfama wander',
        kind: 'neighborhood',
        durationHours: 2.5,
        walkingCostKm: 3.5,
        decisionLoad: 0.55,
        regretWeight: 0.8,
        window: {
          peakHour: 16.5,
          peakWidth: 2,
          crowdAtPeak: 0.5,
          lightAffinity: 'golden',
        },
        priorityTags: ['photo', 'culture', 'nature'],
        description: 'Laneways and fado doorways as the sun slides west.',
      },
      {
        id: 'lx-pastel',
        name: 'Pastéis de Belém',
        kind: 'restaurant',
        durationHours: 0.75,
        walkingCostKm: 0.3,
        decisionLoad: 0.2,
        regretWeight: 0.55,
        window: {
          peakHour: 10,
          peakWidth: 2,
          crowdAtPeak: 0.7,
          lightAffinity: 'day',
        },
        priorityTags: ['food'],
        description: 'Warm custard — shorter queues mid-morning.',
      },
      {
        id: 'lx-fado',
        name: 'Fado night',
        kind: 'nightlife',
        durationHours: 2,
        walkingCostKm: 1,
        decisionLoad: 0.4,
        regretWeight: 0.75,
        window: {
          peakHour: 21.5,
          peakWidth: 2,
          crowdAtPeak: 0.6,
          lightAffinity: 'night',
        },
        priorityTags: ['nightlife', 'culture'],
        description: 'Intimate rooms when your energy still has a second wind.',
      },
      {
        id: 'lx-park',
        name: 'Eduardo VII park rest',
        kind: 'park',
        durationHours: 1,
        walkingCostKm: 1,
        decisionLoad: 0.1,
        regretWeight: 0.25,
        window: {
          peakHour: 14,
          peakWidth: 2,
          crowdAtPeak: 0.3,
          lightAffinity: 'day',
        },
        priorityTags: ['rest', 'nature'],
        description: 'Shade and city axis views — a recovery buffer.',
      },
    ],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    timezoneOffset: 9,
    tagline: 'Layered tempo — neon, shrines, and quiet side streets.',
    experiences: [
      {
        id: 'tyo-sensoji',
        name: 'Sensō-ji at open',
        kind: 'ritual',
        durationHours: 1.5,
        walkingCostKm: 1,
        decisionLoad: 0.3,
        regretWeight: 0.9,
        window: {
          peakHour: 6.5,
          peakWidth: 1.5,
          crowdAtPeak: 0.2,
          lightAffinity: 'dawn',
        },
        priorityTags: ['culture', 'photo'],
        description: 'Incense and empty lanes before Narita day-trippers arrive.',
      },
      {
        id: 'tyo-teamlab',
        name: 'teamLab Planets',
        kind: 'museum',
        durationHours: 2,
        walkingCostKm: 0.6,
        decisionLoad: 0.5,
        regretWeight: 0.65,
        window: {
          peakHour: 11,
          peakWidth: 2.5,
          crowdAtPeak: 0.75,
          lightAffinity: 'day',
        },
        priorityTags: ['culture', 'photo'],
        description: 'Immersive rooms — morning slots protect energy and patience.',
      },
      {
        id: 'tyo-tsukiji',
        name: 'Outer Tsukiji breakfast',
        kind: 'market',
        durationHours: 1.5,
        walkingCostKm: 1.2,
        decisionLoad: 0.6,
        regretWeight: 0.7,
        window: {
          peakHour: 8,
          peakWidth: 1.5,
          crowdAtPeak: 0.55,
          lightAffinity: 'day',
        },
        priorityTags: ['food'],
        description: 'Grilled seafood and coffee while the city is still waking.',
      },
      {
        id: 'tyo-shibuya',
        name: 'Shibuya crossing dusk',
        kind: 'neighborhood',
        durationHours: 1.5,
        walkingCostKm: 2,
        decisionLoad: 0.65,
        regretWeight: 0.6,
        window: {
          peakHour: 18.5,
          peakWidth: 1.5,
          crowdAtPeak: 0.95,
          lightAffinity: 'golden',
        },
        priorityTags: ['photo', 'nightlife'],
        description: 'Neon bloom — only if your crowd tolerance can hold.',
      },
      {
        id: 'tyo-meiji',
        name: 'Meiji Jingu forest',
        kind: 'park',
        durationHours: 1.5,
        walkingCostKm: 2.5,
        decisionLoad: 0.2,
        regretWeight: 0.55,
        window: {
          peakHour: 15,
          peakWidth: 2,
          crowdAtPeak: 0.4,
          lightAffinity: 'day',
        },
        priorityTags: ['nature', 'rest', 'culture'],
        description: 'Canopy hush as an antidote to Midtown density.',
      },
      {
        id: 'tyo-izakaya',
        name: 'Backstreet izakaya',
        kind: 'restaurant',
        durationHours: 2,
        walkingCostKm: 0.8,
        decisionLoad: 0.45,
        regretWeight: 0.7,
        window: {
          peakHour: 19.5,
          peakWidth: 2,
          crowdAtPeak: 0.5,
          lightAffinity: 'night',
        },
        priorityTags: ['food', 'nightlife'],
        description: 'Counter seats when jet lag hasn’t stolen your appetite yet.',
      },
      {
        id: 'tyo-onsen',
        name: 'Sentō soak',
        kind: 'ritual',
        durationHours: 1.5,
        walkingCostKm: 0.5,
        decisionLoad: 0.35,
        regretWeight: 0.5,
        window: {
          peakHour: 21,
          peakWidth: 2,
          crowdAtPeak: 0.35,
          lightAffinity: 'night',
        },
        priorityTags: ['rest'],
        description: 'Heat recovery before circadian crash.',
      },
    ],
  },
  {
    id: 'florence',
    name: 'Florence',
    country: 'Italy',
    timezoneOffset: 1,
    tagline: 'Stone heat, museum gravity, and evening passeggiata.',
    experiences: [
      {
        id: 'fi-duomo',
        name: 'Cupola climb',
        kind: 'viewpoint',
        durationHours: 2,
        walkingCostKm: 0.4,
        decisionLoad: 0.5,
        regretWeight: 0.9,
        window: {
          peakHour: 8,
          peakWidth: 1.5,
          crowdAtPeak: 0.4,
          lightAffinity: 'dawn',
        },
        priorityTags: ['photo', 'culture'],
        description: 'Cooler stone and clearer views before the queue thickens.',
      },
      {
        id: 'fi-uffizi',
        name: 'Uffizi reserved slot',
        kind: 'museum',
        durationHours: 2.5,
        walkingCostKm: 0.5,
        decisionLoad: 0.7,
        regretWeight: 0.85,
        window: {
          peakHour: 10,
          peakWidth: 2,
          crowdAtPeak: 0.7,
          lightAffinity: 'day',
        },
        priorityTags: ['culture'],
        description: 'High decision load — schedule on a high-energy morning.',
      },
      {
        id: 'fi-central',
        name: 'Mercato Centrale',
        kind: 'market',
        durationHours: 1.5,
        walkingCostKm: 0.8,
        decisionLoad: 0.55,
        regretWeight: 0.45,
        window: {
          peakHour: 12,
          peakWidth: 1.5,
          crowdAtPeak: 0.75,
          lightAffinity: 'day',
        },
        priorityTags: ['food'],
        description: 'Upstairs stalls — better before mid-afternoon lethargy.',
      },
      {
        id: 'fi-oltrarno',
        name: 'Oltrarno studios',
        kind: 'neighborhood',
        durationHours: 2,
        walkingCostKm: 2.5,
        decisionLoad: 0.4,
        regretWeight: 0.65,
        window: {
          peakHour: 16,
          peakWidth: 2,
          crowdAtPeak: 0.35,
          lightAffinity: 'golden',
        },
        priorityTags: ['culture', 'photo'],
        description: 'Workshops and quiet squares in soft late light.',
      },
      {
        id: 'fi-ponte',
        name: 'Ponte Vecchio golden hour',
        kind: 'viewpoint',
        durationHours: 0.75,
        walkingCostKm: 0.6,
        decisionLoad: 0.2,
        regretWeight: 0.7,
        window: {
          peakHour: 18.5,
          peakWidth: 1,
          crowdAtPeak: 0.8,
          lightAffinity: 'golden',
        },
        priorityTags: ['photo'],
        description: 'River light — brief, crowded, high regret if missed.',
      },
      {
        id: 'fi-aperitivo',
        name: 'Aperitivo on the Arno',
        kind: 'restaurant',
        durationHours: 1.5,
        walkingCostKm: 0.4,
        decisionLoad: 0.25,
        regretWeight: 0.55,
        window: {
          peakHour: 19.5,
          peakWidth: 1.5,
          crowdAtPeak: 0.55,
          lightAffinity: 'night',
        },
        priorityTags: ['food', 'nightlife', 'rest'],
        description: 'Unwind window before museum fatigue compounds.',
      },
      {
        id: 'fi-giardino',
        name: 'Boboli Gardens rest',
        kind: 'park',
        durationHours: 1.5,
        walkingCostKm: 2,
        decisionLoad: 0.15,
        regretWeight: 0.4,
        window: {
          peakHour: 14.5,
          peakWidth: 2,
          crowdAtPeak: 0.45,
          lightAffinity: 'day',
        },
        priorityTags: ['nature', 'rest'],
        description: 'Shade buffer against afternoon stone heat.',
      },
    ],
  },
];

export function getDestination(id: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.id === id);
}
